version: '3.8'

services:
  ubuntu-vm:
    image: ubuntu:22.04
    container_name: ubuntu-vm
    hostname: ubuntu-vm
    restart: unless-stopped
    ports:
      - "2222:22"  
    volumes:
      - ./storage:/root/storage  
    environment:
      - TZ=UTC
    tty: true
    stdin_open: true